### ISSUE TITLE
Garage door opener

### ISSUE THREAD

**Issue by Supergiovane** [marcus-j-davies/node-red-contrib-homekit-preconfigured#2]
Hello Marcus.
Thank you for this great node's collection. I'm switching from the great homekit bridged node, to your nodes, because i wish to simplify my installation.
Are you planning to add ***garage door opener***? I'ts the only device type missed, then i'll definitely uninstall the homekit bridged node.
Thank you.

**Comment by marcus-j-davies** [comment]
Hi There.
Thanks for the kind feedback.

It should hopefully be a fairly simple job.

Just reading through the HAP Spec for **DOOR**
There are 3 Characteristics that I will need to implement, to get it functional
**CurrentPosition**
**TargetPosition**
**PositionState**

And 2 optional (my aim is to make them fully featured, so I will implement these as well)
**HoldPosition**
**ObstructionDeteced**

I believe the DOOR accessory type, will cater for all, and its a case of changing the icon in HomeApp to represent it being a garage door.

I will look to implement this, in the next couple of days.

**Comment by Supergiovane** [comment]
Thank you Marcus.
There is a garage door specified device, with **own garage icon** and **obstruption detected** property.
If for you is more comfortable, i can do it by myself and push a pull request to your repo, as soon as i finished.

**Comment by marcus-j-davies** [comment]
Ah Nice!

I have just seen the **Garage Door Opener** accessory spec.
I will implement this accessory in the next day or so.

**Comment by Supergiovane** [comment]
Thank you very much. Good job.

**Comment by Supergiovane** [comment]
Here the icon. ;-)

![garage-door-icon](https://user-images.githubusercontent.com/37666636/74422052-3f061400-4e4e-11ea-952a-219fd07f42d9.png)

**Comment by marcus-j-davies** [comment]
Nice!

I have already started to prep, so it shouldn't take me long.
I will be implementing both the **Garage Door** type and the more basic **DOOR** type.

I'm thinking weather or not to have the node include a drop down as to what type of door (Basic, Garage), or have 2 separate nodes.

Thoughts?

**Comment by Supergiovane** [comment]
I think that a combobox should be OK in this case, because it's ever a Garage Door, not another type. Here it make sense for me, thus allow the node to remain simple.

**Comment by Supergiovane** [comment]
Hi
i only know the difference between a door lock and a garage door.
It all depends on icons in the homekit app. Garage Door has own icon, not changeable. Door Lock hat own icon, changeable, but has no garage icon.
Both needs you to authorize the opening by FadeID or TouchID or so..
If basic DOOR is a subtype of a Garage Door, you can go for the dropdown, because the device is the same. The simplicity of the node is not affected in this case.
If not, leave it separate. I love how you've coded the nodes, it's so simple and clean..

**Comment by marcus-j-davies** [comment]
Yup,
The ethos of this project is to remain simple and to the point.
So I will keep to that and keep them separate.

I may not add the basic DOOR type, as it inst something i come across all that often.

Again ,it should be up in a day.

**Comment by Supergiovane** [comment]
I'll wait for it. Thank you.

**Comment by marcus-j-davies** [comment]
Its Done!

It has been published to NPM (and obviously here).
It should be picked up by flows within the hour.

I have not tested it (working away today).
If you could test it for me (when you have the chance), and all being well I will close this down.

Injecting:
```
{
  "payload": "GetCharacteristics"
}
```
Should reveal the Characteristics (I think i got them all).

Let me know how it goes.

**Comment by Supergiovane** [comment]
Thank you. I test it as soon as it appears in the nodered palette. Many thanks.

**Comment by Supergiovane** [comment]
Hello Marcus.
There is a bug. I've no Bugatti Veyron in my garages. Please fix it by sending me a Bugatti.
