### ISSUE TITLE
Request to add configuration example

### ISSUE THREAD

**Issue by 671792320** [marcus-j-davies/node-red-contrib-homekit-preconfigured#4]
Hello

I'm a novice and I don't know how to write these documents

Request to add a sample file for the following related nodes.

Thank you very much for your project. I like it very much, but when I want to access my Sony TV through your project's TV node, I don't know how to write the process of node red. If you can, please add relevant sample configuration to wiki.

The above content comes from machine translation, thanks

**Comment by marcus-j-davies** [comment]
Hi,

I'm working on refactoring this node collection (v2), and apart of that will be to document samples.

However, lets see how we get on in the mean time.

Precursor:
You will need a node(s) that is able to actually control or report from your SONY TV, the
`hk-television` node will not do it by its-self.

The `hk-television` node will emit events out from it, depending on what action had taken place on your iOS device.

**Event** : CharacteristicChange
**Why** :  The TV was was turned off/on, OR its input was changed.

**Event** : ControlAction
**Why** :  The volume was adjusted (side buttons on iOS device) or navigation buttons were pressed. All this takes place in command centre, and then clicking the remote icon.
                  
An example of the input changing (holding down the TV icon) in HomeApp.
```
{
  "event":"CharacteristicChange",
  "characteristic":"ActiveIdentifier",
  "value":3
}
```
What does `value` represent? the 4th input your created on the config screen (and subsequently pressed) , the first being 0.

An example of the TV being turned off (0 - off, 1 - on)
```
{
  "event":"CharacteristicChange",
  "characteristic":"Active",
  "value":0
}
```

Import this to get started - I hope it helps.

`[{"id":"34b497c4.c22488","type":"tab","label":"Flow 1","disabled":false,"info":""},{"id":"8809a7ca.12f48","type":"hk-television","z":"34b497c4.c22488","pincode":"779-53-375","username":"C9:45:26:7A:35:90","name":"Television","port":"52171","interceptget":"No","input_names":"HDMI 1,HDMI 2,HDMI 3","originalId":"8809a7ca.12f48","x":440,"y":380,"wires":[["b6f6d3d8.a90ad"]]},{"id":"4c840d1.114a774","type":"comment","z":"34b497c4.c22488","name":"A node that reports the physical state of TV","info":"","x":190,"y":120,"wires":[]},{"id":"b6f6d3d8.a90ad","type":"function","z":"34b497c4.c22488","name":"Convert message, so it is understood by the next node","func":"if(msg.payload.event == \"CharacteristicChange\")\n{\n    if(msg.payload.characteristic == \"Active\")\n    {\n        return {\"TurnedOn\":msg.payload.value} \n    }\n}","outputs":1,"noerr":0,"x":540,"y":540,"wires":[["dd271859.a353c"]]},{"id":"4bfe1db5.3c9a14","type":"comment","z":"34b497c4.c22488","name":"A node that controls the TV","info":"","x":780,"y":740,"wires":[]},{"id":"c6d3bed7.f1e208","type":"function","z":"34b497c4.c22488","name":"Convert message, so it is understood by the next node","func":"if(msg.payload == \"TurnedOn\")\n{\n    return {\"payload\":{\"Active\":msg.value}}\n    \n}","outputs":1,"noerr":0,"x":460,"y":240,"wires":[["8809a7ca.12f48"]]},{"id":"baf7c017.9a7ca8","type":"function","z":"34b497c4.c22488","name":"Output from TV","func":"\nreturn msg;","outputs":1,"noerr":0,"x":160,"y":160,"wires":[["c6d3bed7.f1e208"]]},{"id":"dd271859.a353c","type":"function","z":"34b497c4.c22488","name":"Input to TV","func":"\nreturn msg;","outputs":1,"noerr":0,"x":690,"y":700,"wires":[[]]},{"id":"80a45fc7.0ba0f8","type":"comment","z":"34b497c4.c22488","name":"Modify HomeApp Status","info":"","x":210,"y":380,"wires":[]},{"id":"efed0f38.f08bb8","type":"comment","z":"34b497c4.c22488","name":"HomeApp Events","info":"","x":640,"y":380,"wires":[]}]`

**Comment by 671792320** [comment]
Hello

Thank you for your reply. Now I have tried again. But I still have some problems

At present, I use Sony's official API to get whether the TV is on, but I don't know how to use function to write the conversion format and send it to HK TV to report that the TV is on.

The contents returned by TV are as follows

`{"result":[{"status":"active"}],"id":50}`

**Comment by marcus-j-davies** [comment]
Hi Based, on that payload, try this in a function node.
Attach the SONY node to the left of it, and the HK node to the right of it.

```
var HKValue = msg.payload.result[0].status == "active" ? 1:0
return {"payload":{"Active":HKValue}}
```

**Comment by 671792320** [comment]
Thank you. It's very easy to use. When I manually perform synchronization, homeapp will synchronize the startup status in time.

I'm trying to write it completely. Thank you very much.

**Comment by marcus-j-davies** [comment]
> Thank you. It's very easy to use. When I manually perform synchronization, homeapp will synchronize the startup status in time.
> 
> I'm trying to write it completely. Thank you very much.

Assuming this worked?

**Comment by 671792320** [comment]
> > 谢谢。它很容易使用。当我手动执行同步时，homeapp将及时同步启动状态。
> > 我正在尝试完全写它。非常感谢你。
> 
> 假设这可行？

Yes, when I manually inject the query status, the icon of homeapp will change accordingly

**Comment by 671792320** [comment]
> > 谢谢。它很容易使用。当我手动执行同步时，homeapp将及时同步启动状态。
> > 我正在尝试完全写它。非常感谢你。
> 
> 假设这可行？
This is my current code
`[
    {
        "id": "d3e678b1.fb6d",
        "type": "tab",
        "label": "Flow 1",
        "disabled": false,
        "info": ""
    },
    {
        "id": "e8cb07a8.801cd",
        "type": "hk-television",
        "z": "d3e678b1.fb6d",
        "pincode": "779-53-375",
        "username": "C9:45:26:7A:35:90",
        "name": "测试三",
        "port": "52171",
        "interceptget": "No",
        "input_names": "HDMI 1,HDMI 2,HDMI 3",
        "originalId": "e8cb07a8.801cd",
        "x": 430,
        "y": 380,
        "wires": [
            [
                "ba528ed4.7eb0f",
                "1cbdedad.760162"
            ]
        ]
    },
    {
        "id": "beb5b47d.ef6618",
        "type": "comment",
        "z": "d3e678b1.fb6d",
        "name": "报告电视物理状态的节点",
        "info": "报告电视物理状态的节点\n\n",
        "x": 140,
        "y": 120,
        "wires": []
    },
    {
        "id": "ba528ed4.7eb0f",
        "type": "function",
        "z": "d3e678b1.fb6d",
        "name": "转换消息，以便下一个节点能够理解它",
        "func": "if(msg.payload.event == \"CharacteristicChange\")\n{\n if(msg.payload.characteristic == \"Active\")\n {\n return {\"TurnedOn\":msg.payload.value} \n }\n}",
        "outputs": 1,
        "noerr": 0,
        "x": 430,
        "y": 540,
        "wires": [
            [
                "85fc271d.38e5"
            ]
        ]
    },
    {
        "id": "b9ae3dde.570d5",
        "type": "comment",
        "z": "d3e678b1.fb6d",
        "name": "控制电视的节点",
        "info": "",
        "x": 750,
        "y": 740,
        "wires": []
    },
    {
        "id": "a591e9eb.28e5a8",
        "type": "function",
        "z": "d3e678b1.fb6d",
        "name": "转换消息，以便下一个节点能够理解它",
        "func": "var HKValue = msg.payload.result[0].status == \"active\" ? 1:0\nreturn {\"payload\":{\"Active\":HKValue}}",
        "outputs": 1,
        "noerr": 0,
        "x": 550,
        "y": 220,
        "wires": [
            [
                "e8cb07a8.801cd",
                "f74b3eb2.b5d82"
            ]
        ]
    },
    {
        "id": "85fc271d.38e5",
        "type": "function",
        "z": "d3e678b1.fb6d",
        "name": "电视输入",
        "func": "\nreturn msg;",
        "outputs": 1,
        "noerr": 0,
        "x": 680,
        "y": 700,
        "wires": [
            [
                "1ffd706b.71e53"
            ]
        ]
    },
    {
        "id": "9ca5cd73.e7b3c",
        "type": "comment",
        "z": "d3e678b1.fb6d",
        "name": "修改HomeApp状态",
        "info": "",
        "x": 150,
        "y": 380,
        "wires": []
    },
    {
        "id": "870daa61.14bdc",
        "type": "comment",
        "z": "d3e678b1.fb6d",
        "name": "家庭应用程序事件",
        "info": "",
        "x": 650,
        "y": 360,
        "wires": []
    },
    {
        "id": "1cbdedad.760162",
        "type": "debug",
        "z": "d3e678b1.fb6d",
        "name": "一",
        "active": true,
        "tosidebar": true,
        "console": false,
        "tostatus": false,
        "complete": "true",
        "targetType": "full",
        "x": 1090,
        "y": 380,
        "wires": []
    },
    {
        "id": "1ffd706b.71e53",
        "type": "debug",
        "z": "d3e678b1.fb6d",
        "name": "二",
        "active": true,
        "tosidebar": true,
        "console": false,
        "tostatus": false,
        "complete": "true",
        "targetType": "full",
        "x": 1130,
        "y": 700,
        "wires": []
    },
    {
        "id": "cfde9656.cdd108",
        "type": "inject",
        "z": "d3e678b1.fb6d",
        "name": "",
        "topic": "",
        "payload": "",
        "payloadType": "date",
        "repeat": "",
        "crontab": "",
        "once": false,
        "onceDelay": 0.1,
        "x": 170,
        "y": 20,
        "wires": [
            [
                "7e1c60c5.ca193"
            ]
        ]
    },
    {
        "id": "d366e234.6d40c",
        "type": "debug",
        "z": "d3e678b1.fb6d",
        "name": "",
        "active": true,
        "tosidebar": true,
        "console": false,
        "tostatus": false,
        "complete": "true",
        "targetType": "full",
        "x": 1030,
        "y": 40,
        "wires": []
    },
    {
        "id": "7e1c60c5.ca193",
        "type": "function",
        "z": "d3e678b1.fb6d",
        "name": "获取电视状态",
        "func": "msg.headers = {\n    \"Content-Type\": \"application/json; charset=UTF-8\",\n   \"X-Auth-PSK\": \"sony\"\n}\nmsg.payload = {\n    \"method\": \"getPowerStatus\",\n    \"id\": 50,\n    \"params\": [],\n    \"version\": \"1.0\"\n}\nreturn msg;",
        "outputs": 1,
        "noerr": 0,
        "x": 360,
        "y": 40,
        "wires": [
            [
                "788ac5ac.67992c"
            ]
        ]
    },
    {
        "id": "788ac5ac.67992c",
        "type": "http request",
        "z": "d3e678b1.fb6d",
        "name": "",
        "method": "POST",
        "ret": "txt",
        "paytoqs": false,
        "url": "http://192.168.1.99/sony/system",
        "tls": "",
        "persist": false,
        "proxy": "",
        "authType": "",
        "x": 540,
        "y": 40,
        "wires": [
            [
                "d366e234.6d40c",
                "4a59c3b7.a38dbc"
            ]
        ]
    },
    {
        "id": "f74b3eb2.b5d82",
        "type": "debug",
        "z": "d3e678b1.fb6d",
        "name": "",
        "active": true,
        "tosidebar": true,
        "console": false,
        "tostatus": false,
        "complete": "true",
        "targetType": "full",
        "x": 880,
        "y": 300,
        "wires": []
    },
    {
        "id": "4a59c3b7.a38dbc",
        "type": "json",
        "z": "d3e678b1.fb6d",
        "name": "",
        "property": "payload",
        "action": "",
        "pretty": true,
        "x": 540,
        "y": 140,
        "wires": [
            [
                "a591e9eb.28e5a8"
            ]
        ]
    }
]`

**Comment by marcus-j-davies** [comment]
You can use the inject node, to trigger the flow (which will fetch the status from SONY and return it to HK) see attached
![Capture](https://user-images.githubusercontent.com/55892693/74822898-c09dec00-52fd-11ea-9928-782b4893550f.PNG)
.

**Comment by 671792320** [comment]
> You can use the inject node, to trigger the flow (which will fetch the status from SONY and return it to HK) see attached
> ![Capture](https://user-images.githubusercontent.com/55892693/74822898-c09dec00-52fd-11ea-9928-782b4893550f.PNG)
> .

What is attached?

**Comment by 671792320** [comment]
> You can use the inject node, to trigger the flow (which will fetch the status from SONY and return it to HK) see attached
> ![Capture](https://user-images.githubusercontent.com/55892693/74822898-c09dec00-52fd-11ea-9928-782b4893550f.PNG)
> .

Yes, I haven't used the timing trigger to get the current status.

**Comment by marcus-j-davies** [comment]
I thought the image will not show up (but it did)
In essence, instead of manually triggering it all, use the inject node to run every n interval
![Capture](https://user-images.githubusercontent.com/55892693/74823457-a1538e80-52fe-11ea-9c81-5da228e01139.PNG)
 .

**Comment by 671792320** [comment]
Sorry, I just used Baidu Translate and did n’t understand what you meant. I now understand what you mean. Thank you

**Comment by 671792320** [comment]
There is a question I don't know if I can make it clear.
HK-TV has been turned on in the homeapp, but when I send the command through the remote control of the control center, I will send the power-on command again. What should I do?
Because i use braiva-ircc for sony node
If the TV is powered on, if it receives the power-on instruction for the second time, the TV will be turned off, because IRCC uses the infrared command sent by the network.

**Comment by marcus-j-davies** [comment]
Yup!

This is an iOS behavior (I think), I also have the same problem, I am not sure why iOS does that.
what you can do is (and what I do)

The flow that will control the On/Off state, put a RBE node right before it goes to the TV.
and set it to 'Block Unless Value changes'.

This will stop a message getting thorough , if the last message was the same, as the one trying to get through.

**Comment by 671792320** [comment]
Okay, thanks.
Hope it didn't bother you
I will try again

**Comment by marcus-j-davies** [comment]
not at all - you are very welcome.

**Comment by marcus-j-davies** [comment]
This project is no longer maintained
