### ISSUE TITLE
Questions about camera hardware decoding

### ISSUE THREAD

**Issue by 671792320** [marcus-j-davies/node-red-contrib-homekit-preconfigured#5]
Hello, please ask for help on the camera, when I try to use ffmpeg to hard decode the problem
I query the official hardware decode for this command
-vaapi_device / dev / dri / renderD128 -hwaccel vaapi -hwaccel_output_format vaapi
When I add it like this and add monitoring rtsp connection, it seems to be unable to start, I am confused why this is not possible? But the same command can be started normally under homeassistant.
In addition, I found that ffmpeg seems to support Intel QSV, but what I installed from apk add ffmpeg didn't seem to compile. I tried to recompile ffmpeg myself but it failed.
My installation platform is nodered with a black skirt black DS918 + 6.2.2 docker installation.
When I execute ls / dev / dri under nodered, docker correctly recognizes renderD128

**Comment by 671792320** [comment]
It seems that when I use it under homeassistant like this -vaapi_device / dev / dri / renderD128 -hwaccel vaapi -hwaccel_output_format vaapi
My homeassistant cannot restart the docker container anymore

**Comment by marcus-j-davies** [comment]
Hi

I have not experimented much with ffmpeg.

use these settings, and let me know if they work.

**Source Stream:** -rtsp_transport tcp -i rtsp://url_for_camera_stream
**Encoder:** libx264

it maybe that the user account the process is running under, does not have access to certain hardware.

I use **h264_omx** and it runs pretty well.

**Comment by marcus-j-davies** [comment]
actually **h264_omx** won't work if running on a NAS.
try **libx264** instead

**Comment by 671792320** [comment]
> 实际上，如果在NAS上运行，则**h264_omx**无法正常工作。
> 尝试**libx264**代替

Mine is DS918 + installed by J1900 without h264_omx
This is H264 supported by ffmpeg installed in my NAS
om --arch = x86_64 --enable-vaapi --enable-libmfx
   libavutil 56. 31.100 / 56. 31.100
   libavcodec 58. 54.100 / 58. 54.100
   libavformat 58. 29.100 / 58. 29.100
   libavdevice 58. 8.100 / 58. 8.100
   libavfilter 7. 57.100 / 7. 57.100
   libavresample 4. 0. 0 / 4. 0. 0
   libswscale 5. 5.100 / 5. 5.100
   libswresample 3. 5.100 / 3. 5.100
   libpostproc 55. 5.100 / 55. 5.100
  DEV.LS h264 H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10 (decoders: h264 h264_qsv) (encoders: libx264 libx264rgb h264_qsv h264_vaapi)

**Comment by 671792320** [comment]
When I use libx264 or h264 when my phone is turned on for monitoring, the CPU load of the NAS is 50% or higher

**Comment by marcus-j-davies** [comment]
ok...

fire up 'top' in terminal and capture the ffmpeg process - it will give you the exact argument being passed to ffmpeg, when viewing a stream in Homekit

then use that same argument in a terminal  - ffmpeg should return with some errors.
I haven't enabled much in the way of debugging the nodes currently

**Comment by 671792320** [comment]
OK, do I use parameters that enable hardware decoding? Or is it the default parameter?
Should I completely copy the parameters that homekit passes to ffmpeg?

**Comment by marcus-j-davies** [comment]
configure the node, as you would like.
Then once done. fire up top like this 'top -c'

then view the stream in Homewkit
![Screenshot 2020-02-26 at 14 19 56](https://user-images.githubusercontent.com/55892693/75353449-55c35680-58a3-11ea-9905-7ab1ac0ac46d.png)


top will capture the arguments.
when you have got the exact command from top - run that same command in terminal and see what output ffmpeg gives you.

**Comment by 671792320** [comment]
Complete command
ffmpeg -vaapi_device / dev / dri / renderD128 -hwaccel vaapi -hwaccel_output_format vaapi -i rtsp: // admin: 123@192.168.1.242: 8554 / live3.sdp -map 0: 0 -vcodec h264 -pix_fmt yuv420p -r 10 -f rawvideo -tune zerolatency -vf scale = 1280: 720 -b: v 299k -bufsize 299k -maxrate 299k -payload_type 99 -ssrc 6393353 -f rtp -srtp_out_suite AES_CM_128_HMAC_SHA1_80 -1.2? crtv_crc1_cwc1c1xwc1c1xwc1c1c1c1c2c1c1c1c2c1c1c1c2 = 61774 & pkt_size = 1316


Prompt this directly in the terminal
bash-5.0 # ffmpeg version 4.2.1 Copyright (c) 2000-2019 the FFmpeg developers
  built with gcc 9.2.0 (Alpine 9.2.0)
  configuration: --prefix = / usr --enable-avresample --enable-avfilter --enable-gnutls --enable-gpl --enable-libass --enable-libmp3lame --enable-libvorbis --enable-libvpx- enable-libxvid --enable-libx264 --enable-libx265 --enable-libtheora --enable-libv4l2 --enable-postproc --enable-pic --enable-pthreads --enable-shared --enable-libxcb- disable-stripping --disable-static --disable-librtmp --enable-vaapi --enable-vdpau --enable-libopus --disable-debug
  libavutil 56. 31.100 / 56. 31.100
  libavcodec 58. 54.100 / 58. 54.100
  libavformat 58. 29.100 / 58. 29.100
  libavdevice 58. 8.100 / 58. 8.100
  libavfilter 7. 57.100 / 7. 57.100
  libavresample 4. 0. 0 / 4. 0. 0
  libswscale 5. 5.100 / 5. 5.100
  libswresample 3. 5.100 / 3. 5.100
  libpostproc 55. 5.100 / 55. 5.100

[3] + Done localrtcpport = 61774
Seems no problem.

**Comment by 671792320** [comment]
![QQ截图20200226222703](https://user-images.githubusercontent.com/10532894/75353964-2d5d4b80-58e7-11ea-8624-17aa0723908f.png)

**Comment by marcus-j-davies** [comment]
and I guessing no stream is getting to the phone?

**Comment by 671792320** [comment]
No output on the phone

**Comment by marcus-j-davies** [comment]
ok..

edit the command (and run in terminal) and instead  of sending out to the phone, save it to file

ffmpeg -vaapi_device / dev / dri / renderD128 -hwaccel vaapi -hwaccel_output_format vaapi -i rtsp: // admin: 123@192.168.1.242: 8554 / live3.sdp -map 0: 0 -vcodec h264 -pix_fmt yuv420p -r 10 -f rawvideo -tune zerolatency -vf scale = 1280: 720 -b: v 299k -bufsize 299k -maxrate 299k video.mp4

if that still does not produce a viewable  file (you will need to ctrl+c it) then we have pinpointed it down to ffmpeg.

**Comment by 671792320** [comment]
OK, I'll test it.
If there is still no output then ffmpeg is not working, is it?

**Comment by 671792320** [comment]
Prompt this [rtsp @ 0x7f1f12fc5540] method DESCRIBE failed: 401 Unauthorized
rtsp :: Server returned 401 Unauthorized (authorization failed)

And docker is not responding, you need to restart nas before

**Comment by marcus-j-davies** [comment]
that's from ffmpeg?

**Comment by 671792320** [comment]
No, just because of the url space problem, I am now restarting nas

**Comment by 671792320** [comment]
Seems to be a problem with the docker container not recognizing the hardware
[AVHWDeviceContext @ 0x7f77c4ae8380] No VA display found for device / dev / dri / renderD128.
Device creation failed: -22.
Failed to set value '/ dev / dri / renderD128' for option 'vaapi_device': Invalid argument
Error parsing global options: Invalid argument
![123](https://user-images.githubusercontent.com/10532894/75355564-ab225680-58e9-11ea-8ee7-4465bbaee8f2.png)

**Comment by marcus-j-davies** [comment]
There you go!
I'm no expert at ffmpeg I'm afraid. it may Evan be docker not being able to access or see the hardware - again I'm not an expert in docker either (.Net and NodeJS are my thing)

its defintetly   a hardwire config/access problem as software rendering (libx264 is fine) apart from the high CPU usage to course.

hardware rendering on a pi (using **h264_omx**) does work really well however,
not sure what else I can say here - sorry.

**Comment by 671792320** [comment]
Thanks for your help, I try to add hardware mapping when starting docker. In the end, I will give you feedback if it has any effect.
Thank you

**Comment by marcus-j-davies** [comment]
thanks.

let me know how it goes.

**Comment by 671792320** [comment]
You're welcome

**Comment by 671792320** [comment]
It seems normal now.
You need docker run --name nodered --device = / dev / dri: / dev / dri nodered / node-red when starting docker
The purpose of this is to map the graphics card and then install it under docker
ffmpeg and libva-intel-driver, so you can properly drive vaapi for hard solution.
If docker prompts no permission, please connect docker image with root privileges
docker exec -it -u root xxx / bin / bash
Then you can use apk add ffmpeg and libva-intel-driver
Thank you for your answer, thank you
![3](https://user-images.githubusercontent.com/10532894/75358364-b9727180-58ed-11ea-9c42-1c5ec6af6fa9.png)

**Comment by marcus-j-davies** [comment]
And this also now works in node red using the camera node?

**Comment by 671792320** [comment]
I'm not testing under nodered right now because it was built using a temporary environment and cannot be tested under nodered. I'll wait to re-establish nodered for testing. Then I will tell you. xie

**Comment by 671792320** [comment]
After trying, it won't start if using vaapi.
Thank you

**Comment by marcus-j-davies** [comment]
Ok - Lets take a step back, and do this a different way.

Setup node as required (Don't be bias for this debugging)

Find the prototype : `Camera.prototype.handleStreamRequest` in `camera.js`
In here, add the ability to capture `stderr` from the `ffmpeg `process.

Under
`const ffmpeg = spawn("ffmpeg", fcmd.split(' '), { env: process.env, })`
Add
```
ffmpeg.stdout.on('data', function(data)
{
     console.log(data)
})
ffmpeg.stderr.on('data', function(data)
{
     console.log(data)
})
```
Then run node-red, but in a terminal.
attempt to view stream on iOS device

The terminal will (Should) report any error output from ffmpeg

**Comment by 671792320** [comment]
![1](https://user-images.githubusercontent.com/10532894/75602961-109e5f00-5b05-11ea-88a6-141f33af4063.png)
![2](https://user-images.githubusercontent.com/10532894/75602963-12682280-5b05-11ea-9218-b653345ff733.png)
When I use the parameters that I can use before, after adding the code according to your prompt, turning on the camera, I get a string in the background. Then the homekit camera eventually stopped and there was no image output.
In addition, I checked the Wiki and learned that my central processor J1900 is using a Z3700 series graphics card, GEN7 generation, VAAPI does not support decoding, but supports encoding.
I read these on the website introduced by vaapi This is a link to the content http://trac.ffmpeg.org/wiki/Hardware/VAAPI
Encoding
The encoders only accept input as VAAPI surfaces. If the input is in normal memory, it will need to be uploaded before giving the frames to the encoder-in the ffmpeg utility, the hwupload filter can be used for this. It will upload to a surface with the same layout as the software frame, so it may be necessary to add a format filter immediately before to get the input into the right format (hardware generally wants the nv12 layout, but most software functions use the yuv420p layout). The hwupload filter also requires a device to upload to, which needs to be defined before the filter graph is created.

So, to use the default decoder for some input, then upload frames to VAAPI and encode with H.264 and default settings:

ffmpeg -vaapi_device / dev / dri / renderD128 -i input.mp4 -vf 'format = nv12, hwupload' -c: v h264_vaapi output.mp4
If the input is known to be hardware-decodable, then we can use the hwaccel:

ffmpeg -hwaccel vaapi -hwaccel_output_format vaapi -hwaccel_device / dev / dri / renderD128 -i input.mp4 -c: v h264_vaapi output.mp4
Finally, when the input may or may not be hardware decodable we can do:

ffmpeg -init_hw_device vaapi = foo: / dev / dri / renderD128 -hwaccel vaapi -hwaccel_output_format vaapi -hwaccel_device foo -i input.mp4 -filter_hw_device foo -vf 'format = nv12 | vaapi, hwupload' -c: v h264_vaapi
This works because the decoder will output either vaapi surfaces (if the hwaccel is usable) or software frames (if it isn't). In the first case, it matches the vaapi format and hwupload does nothing (it passes through hardware frames unchanged) . In the second case, it matches the nv12 format and converts whatever the input is to that, then uploads. Performance will likely vary by a large amount depending which path is chosen, though.

The supported encoders are:

H.262 / MPEG-2 part 2 mpeg2_vaapi
H.264 / MPEG-4 part 10 (AVC) h264_vaapi
H.265 / MPEG-H part 2 (HEVC) hevc_vaapi
MJPEG / JPEG mjpeg_vaapi
VP8 vp8_vaapi
VP9 vp9_vaapi
For an explanation of codec options, see <http://www.ffmpeg.org/ffmpeg-codecs.html#VAAPI-encoders>.

**Comment by 671792320** [comment]
![2222](https://user-images.githubusercontent.com/10532894/75603247-ae932900-5b07-11ea-91c1-29f4db8a8c9f.png)
Correct it, there is no problem with the default parameters, everything is normal.
Only I changed -vcodec to h264_vaapi, ffmpeg does not start, and there is no error message in the terminal.

**Comment by marcus-j-davies** [comment]
Sorry change
`console.log(data)`
to 
`console.log(data.toString())`

and run it again (viewing a stream on your iOS device) (run node-red in terminal)

**Comment by 671792320** [comment]
https://wiki.archlinux.org/index.php/Hardware_video_acceleration#Comparison_tables
Can you help me confirm that my J1900 processor supports VAAPI hardware encoding? Or QSV encoding

**Comment by 671792320** [comment]
Can you see if this can be solved?
![444444](https://user-images.githubusercontent.com/10532894/75603986-287ae080-5b0f-11ea-8531-9cd925958af2.png)

**Comment by marcus-j-davies** [comment]
Ok,

can you send me your 'Source Stream' parameter.

**Comment by 671792320** [comment]
is this one?
bash-5.0# ffmpeg -rtsp_transport tcp -i rtsp://admin:123@192.168.1.247:8554/live0.sdp
ffmpeg version 4.2.1 Copyright (c) 2000-2019 the FFmpeg developers
  built with gcc 9.2.0 (Alpine 9.2.0)
  configuration: --prefix=/usr --enable-avresample --enable-avfilter --enable-gnutls --enable-gpl --enable-libass --enable-libmp3lame --enable-libvorbis --enable-libvpx --enable-libxvid --enable-libx264 --enable-libx265 --enable-libtheora --enable-libv4l2 --enable-postproc --enable-pic --enable-pthreads --enable-shared --enable-libxcb --disable-stripping --disable-static --disable-librtmp --enable-vaapi --enable-vdpau --enable-libopus --disable-debug
  libavutil      56. 31.100 / 56. 31.100
  libavcodec     58. 54.100 / 58. 54.100
  libavformat    58. 29.100 / 58. 29.100
  libavdevice    58.  8.100 / 58.  8.100
  libavfilter     7. 57.100 /  7. 57.100
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  5.100 /  5.  5.100
  libswresample   3.  5.100 /  3.  5.100
  libpostproc    55.  5.100 / 55.  5.100
Input #0, rtsp, from 'rtsp://admin:123@192.168.1.247:8554/live0.sdp':
  Metadata:
    title           : Session Streamed by LIBZRTSP
    comment         : live0.sdp
  Duration: N/A, start: 0.085000, bitrate: N/A
    Stream #0:0: Video: h264 (Main), yuvj420p(pc, bt709, progressive), 1920x1080, 23.42 tbr, 90k tbn, 180k tbc
At least one output file must be specified
bash-5.0# 
My current network environment is not stable, and my visit to github.com may be slow.

**Comment by 671792320** [comment]
![112233](https://user-images.githubusercontent.com/10532894/75604110-59a7e080-5b10-11ea-8552-c496b3a4d20f.png)
Or this one

**Comment by marcus-j-davies** [comment]
that's the one.

I am on a Mac, so going to to configure it myself, and see what I get

**Comment by marcus-j-davies** [comment]
Bear with me....

**Comment by 671792320** [comment]
Thank you. Because I am not very proficient in compilation, I also tried to compile ffmpeg to open Intel QSV and vaapi, but it failed. The static compiled version of ffmpeg file I found on the network does not support the above two protocols

**Comment by marcus-j-davies** [comment]
your nas is x86, as I am on a Mac, I should be bale to reproduce what's going on,

**Comment by marcus-j-davies** [comment]
Ok, the static build for OSX doesn't include vaapi
`Unknown encoder 'h264_vaapi'`

I don't have the means to compile currently, so not sure how much more I can offer.

**Comment by 671792320** [comment]
OK, thank you for your help

**Comment by marcus-j-davies** [comment]
Question,

does node-red run with root privileges?
during this conversation you have had it working. - what has changed from the below?


> It seems normal now.
> You need docker run --name nodered --device = / dev / dri: / dev / dri nodered / node-red when starting docker
> The purpose of this is to map the graphics card and then install it under docker
> ffmpeg and libva-intel-driver, so you can properly drive vaapi for hard solution.
> If docker prompts no permission, please connect docker image with root privileges
> docker exec -it -u root xxx / bin / bash
> Then you can use apk add ffmpeg and libva-intel-driver
> Thank you for your answer, thank you
> ![3](https://user-images.githubusercontent.com/10532894/75358364-b9727180-58ed-11ea-9c42-1c5ec6af6fa9.png)

**Comment by 671792320** [comment]
已经给docker已dsm的高权限去运行、并且映射了显卡硬件、
我想我已经知道了问题的所在了。
ffmpeg -rtsp_transport tcp  -i rtsp://admin:123@192.168.1.472:8554/live3.sdp -map 0:0 -vcodec h264_vaapi -pix_fmt yuv420p  -r 10 -f rawvideo -tune zerolatency -vf scale=1280:720 -b:v 299k -bufsize 299k -maxrate 299k -payload_type 99 -ssrc 6571014 -f rtp -srtp_out_suite AES_CM_128_HMAC_SHA1_80 -srtp_out_params Lt+aaxTM650UQslZMLwOb/bciq3DuSBCIE98A5AS srtp://192.168.1.243:63686?rtcpport=63686&localrtcpport=63686&pkt_size=1316
这段命令是homekit工作是否的状态、
我在用你给的调试文件测试的时候发现。
我这样运行会出现提示vppi无法解码、我按照Wiki指示将-pix_fmt yuv420p 修改为-pix_fmt nv12,hwupload同样会报错、因为这个是先加载文件然后使用h264进行转码为yuv420格式后在发串流到homekit。但是我并没有在wiki上找到相关的内容示例、或许这样行不通。您的树莓派h264_omx似乎直接支持这样的格式、但是在vaapi上不行，并且提示vaapi_vld，但是我查询ffmpeg似乎并没有这样选项。也就是VAAPI不支持这样的格式。
遗憾的是我没有办法是用intel qsv进行测试。因为docker是基于alpine制作的nodered-我安装的ffmpeg并不支持qsv
The docker has been given high permission to run DSM, and mapped the hardware of the graphics card

I think I already know the problem.

ffmpeg -rtsp_transport tcp -i rtsp://admin:123@192.168.1.472:8554/live3.sdp -map 0:0 -vcodec h264_vaapi -pix_fmt yuv420p -r 10 -f rawvideo -tune zerolatency -vf scale=1280:720 -b:v 299k -bufsize 299k -maxrate 299k -payload_type 99 -ssrc 6571014 -f rtp -srtp_out_suite AES_CM_128_HMAC_SHA1_80 -srtp_out_params Lt+aaxTM650UQslZMLwOb/bciq3DuSBCIE98A5AS srtp://192.168.1.243:63686?rtcpport=63686&localrtcpport=63686&pkt_size=1316

This command is the status of whether homekit works

I found it when I tested it with the debugging file you gave me.

When I run like this, I will be prompted that VPPI cannot be decoded. I will change - pix ﹣ FMT yuv420p to - pix ﹣ FMT nv12 according to the instructions of Wiki. Hwupload will also report an error, because this is to load the file first, then transcode it to YUV420 format using h264, and then send it to homekit. But I didn't find relevant content samples on Wiki, which may not work. Your raspberry pie H264 ﹣ OMX seems to support this format directly, but not on vaapi, and prompts vaapi ﹣ VLD, but I don't seem to have this option when querying ffmpeg. That is, vaapi does not support this format.

**Comment by marcus-j-davies** [comment]
This might be of interest.
the camera node is based on homebridge-camera-ffmpeg

https://github.com/KhaosT/homebridge-camera-ffmpeg/issues/306

**Comment by 671792320** [comment]
It seems that I'm not the first one to find out the second problem

It seems interesting

**Comment by marcus-j-davies** [comment]
the `-vf` parameter is used to to scale down the video (HomeKit asks for different resolutions) based on the device - you can try setting this manually (by editing the js file).

`-vf "format=nv12,hwupload"`

**Comment by 671792320** [comment]
Is that right?

![666666](https://user-images.githubusercontent.com/10532894/75605799-0ee29480-5b21-11ea-835f-7b21f0822360.png)

**Comment by marcus-j-davies** [comment]
should be.

**Comment by 671792320** [comment]
ok

**Comment by marcus-j-davies** [comment]
you have missed of `fps` after -r

**Comment by marcus-j-davies** [comment]
give me a sec

**Comment by marcus-j-davies** [comment]
use this, in place of the original 

`const ffmpegInputArgs = ' -map ' + mapvideo + ' -vcodec ' + vcodec + ' -pix_fmt yuv420p -r ' + fps + ' -f rawvideo' + ' ' + additionalCommandline + ' -vf "format=nv12,hwupload" -b:v ' + vbitrate + 'k' + ' -bufsize ' + vbitrate + 'k' + ' -maxrate ' + vbitrate + 'k' + ' -payload_type 99'`

**Comment by 671792320** [comment]
ok

**Comment by 671792320** [comment]
![21](https://user-images.githubusercontent.com/10532894/75605932-abf1fd00-5b22-11ea-8825-a2eb99879e9d.png)
![221](https://user-images.githubusercontent.com/10532894/75605933-adbbc080-5b22-11ea-865b-f5a38b1b3964.png)

**Comment by marcus-j-davies** [comment]
the `-re` has caused me probed in the past - try it with and without

**Comment by marcus-j-davies** [comment]
isn't that the problem you had last time - where the driver was not installed?

**Comment by 671792320** [comment]
I'm very sure that I have the driver installed

**Comment by 671792320** [comment]
![33333333](https://user-images.githubusercontent.com/10532894/75605989-5a963d80-5b23-11ea-8ee8-db0083b30eaf.png)

**Comment by marcus-j-davies** [comment]
put video.mp4 at the end

**Comment by 671792320** [comment]
![44444](https://user-images.githubusercontent.com/10532894/75606023-ac3ec800-5b23-11ea-8dd6-69e1b90f5602.png)
![55555](https://user-images.githubusercontent.com/10532894/75606024-aea12200-5b23-11ea-83cd-2122e2529bb5.png)

**Comment by marcus-j-davies** [comment]
ok so clearly the `-vf` fix is working.

other than hardware access issues with node-red, I can't see any reason why it will not work.

it could be : 
The use of `docker` getting in the way
`node-red` its self not having the right access (does it have root)
the nodejs module `child_process` having problems - its used to start ffmpeg.

everything works for you when using libx264, I use hardware rendering, so I can only point to an issue with permissions or docker.

Sorry - I can't offer anything else.

**Comment by 671792320** [comment]
ok

**Comment by 671792320** [comment]
Is your noed-red running inside a docker container? Or run directly on the Raspberry Pi

**Comment by 671792320** [comment]
Can you help me modify this code with the file?

ffmpeg -hwaccel vaapi -vaapi_device /dev/dri/renderD128 \

-threads:v 2 -threads:a 4 \

-rtsp_transport tcp \

-i rtsp://admin:123@192.168.1.247:8554/live3.sdp \

-map 0:0 \

-pix_fmt yuv420p \

-r 15.

-f rawvideo \

-vf 'format=nv12|vaapi,hwupload,scale_vaapi=1280:720' \

-c:v h264_vaapi \

-b:v 299k \

-bufsize 299k \

-maxrate 299k -payload_type 99 \

-ssrc 13314026 \

-f RTP \

-srtp_out_suite AES_CM_128_HMAC_SHA1_80 \

-srtp_out_params ils+c7v2WkNjdFFgICwYAeDKZ5oVaUAs1moiaGFB \

"srtp://192.168.1.243:62485?rtcpport=62485&localrtcpport=62485&pkt_size=1316"

This is me at https://gist.github.com/brainiarc7/95c9338a737aa36d9bb2931bed379219

Answers found on
![123123](https://user-images.githubusercontent.com/10532894/75618874-0d5fad80-5baf-11ea-94da-f27270ea8a7a.png)
![234234](https://user-images.githubusercontent.com/10532894/75618875-0fc20780-5baf-11ea-83f0-bf83973db7b0.png)

**Comment by marcus-j-davies** [comment]
Morning,

No worries, so you want to use the command from Braniark7 yes?

**Comment by 671792320** [comment]
I want to test it

**Comment by marcus-j-davies** [comment]
ok let me just modify the JS file and I will attach it here... bear with me.

**Comment by marcus-j-davies** [comment]
**Step 1:**
Replace the Camera.js file, with this one attached.

**step 2:**
Set this as the `Source Stream`
```
-hwaccel vaapi -vaapi_device /dev/dri/renderD128 -threads:v 2 -threads:a 4 -rtsp_transport tcp -i rtsp://STREAM_URL
```

**Step 3:**
set `h264_vaapi` as the encocder

[Camera.js.zip](https://github.com/marcus-j-davies/node-red-contrib-homekit-preconfigured/files/4271571/Camera.js.zip)

**Comment by marcus-j-davies** [comment]
hangon - let me just add debugging to it.....

**Comment by marcus-j-davies** [comment]
ok this on
[Camera.js.zip](https://github.com/marcus-j-davies/node-red-contrib-homekit-preconfigured/files/4271573/Camera.js.zip)

**Comment by marcus-j-davies** [comment]
run node -red in terminal (so we can see any output)

**Comment by 671792320** [comment]
ok I'll wait for the test

**Comment by 671792320** [comment]
It seems that we have to give up.
![123](https://user-images.githubusercontent.com/10532894/75647286-7d416700-5c87-11ea-908b-03b6cd8c4705.png)

**Comment by marcus-j-davies** [comment]
The only thing that could cause that i guess is 
-vaapi_device. being set to a non valid Render device. Or the url for the camera being incorrect.

**Comment by 671792320** [comment]
yes

**Comment by marcus-j-davies** [comment]
I don't think there is much more one can do here, not from a node specific point of view.
after all the testing, I can only put this down to some DSM/Node-Red/Docker environment factor, causing the issue.

Sorry, I couldn't resolve.

**Comment by 671792320** [comment]
“ srtp：//192.168.1.243：62485？rtcpport = 62485＆localrtcpport = 62485＆pkt_size = 1316”
This command, I found that you have not added "" or "" in the modified file. I found that when I input all the commands, if the lowest STRP is not in "", the process will not start.
