### ISSUE TITLE
Please forgive me for opening a new request.

### ISSUE THREAD

**Issue by 671792320** [marcus-j-davies/node-red-contrib-homekit-preconfigured#6]
ffmpeg -hwaccel vaapi -vaapi_device /dev/dri/renderD128 \
...
-srtp_out_params ils+c7v2WkNjdFFgICwYAeDKZ5oVaUAs1moiaGFB \
"srtp://192.168.1.243:62485?rtcpport=62485&localrtcpport=62485&pkt_size=1316"

In the above. If SRTP: / / is not entered by '' or '' then the entire command will not take effect.

Here are the screenshots.

![1](https://user-images.githubusercontent.com/10532894/75767424-c542b580-5d7d-11ea-84d9-1ff90e54fbef.png)
![2](https://user-images.githubusercontent.com/10532894/75767428-c673e280-5d7d-11ea-9604-c9c17d7644c8.png)
The command in the first figure has a band '', I tested that both '' and '' can open the process normally

The second graph doesn't have '' or '' will stick like this

**Comment by marcus-j-davies** [comment]
Hi,

This is a very isolated issue/environmental factor.

Every project that I have come across that offers homekit camera functionality, does not require the URI's to be quoted. The developer of **homebridge-camera-ffmpeg**, does not Evan have it quoted.
https://github.com/KhaosT/homebridge-camera-ffmpeg/blob/master/ffmpeg.js

And that same developer, is who has developed the NodeJS Homekit lib that these nodes use.

I myself do not have it quoted.

In an effort to get this working for you.
I have replaced the single quotes around the **-vf** attribute with double quotes. see if that helps.

[Camera.zip](https://github.com/marcus-j-davies/node-red-contrib-homekit-preconfigured/files/4280890/Camera.zip)

**Comment by 671792320** [comment]
LIVE555 Streaming Media v2013.04.06
  Duration: N/A, start: -23435.054967, bitrate: N/A
    Stream #0:0: Video: h264 (Main), yuv420p(progressive), 1280x720, 50 fps, 25 tbr, 90k tbn, 100 tbc
Option hwaccel (use HW accelerated decoding) cannot be applied to output url  -- you are trying to apply an input option to an output file or vice versa. Move this option before the file it belongs to.
Error parsing options for output file .
Error opening output files: Invalid argument

**Comment by marcus-j-davies** [comment]
Sorry, I have no idea what this is referring to, why is LIVE555 involved?
Are you pointing the `Source Stream` to a LIVE555 stream?

`hwaccel `should come before your -i argument 

**Source Stream**
`-hwaccel vaapi -vaapi_device /dev/dri/renderD128 -threads:v 2 -threads:a 4 -rtsp_transport tcp -i rtsp://STREAM_URL`

**Encoder**
`h264_vaapi `

**Comment by 671792320** [comment]
![3](https://user-images.githubusercontent.com/10532894/75773457-e8bf2d80-5d88-11ea-8cde-8467c3c8b228.png)

**Comment by 671792320** [comment]
![4](https://user-images.githubusercontent.com/10532894/75773594-2b810580-5d89-11ea-83bb-3a1482fd3200.png)

**Comment by 671792320** [comment]
![5](https://user-images.githubusercontent.com/10532894/75773974-e7423500-5d89-11ea-9757-f3d8cc9878ce.png)

**Comment by marcus-j-davies** [comment]
in the **camera.js** file change (exactly as shown)

`"format=nv12|vaapi,hwupload,scale_vaapi='+width+':'+height+'"`
to
`format="nv12|vaapi,hwupload,scale_vaapi='+width+':'+height+'"`

putting the double  quote after the `=` and not before

**Comment by 671792320** [comment]
![6](https://user-images.githubusercontent.com/10532894/75775579-3c337a80-5d8d-11ea-9659-5059b50db89b.png)
Really not? It's strange why that code can run normally under Bash and can't be opened on the mobile phone.

**Comment by marcus-j-davies** [comment]
try taking the double quotes out completely 

`-vf format=nv12|vaapi,hwupload,scale_vaapi='+width+':'+height+'`

**Comment by 671792320** [comment]
![7](https://user-images.githubusercontent.com/10532894/75776318-bc0e1480-5d8e-11ea-9f12-31c80eec03d1.png)
Seems to be back to the beginning

**Comment by 671792320** [comment]
![8](https://user-images.githubusercontent.com/10532894/75776591-38085c80-5d8f-11ea-804e-941f33f5897e.png)
Does it seem that the ffmpeg I installed does not support nv12 format?

**Comment by marcus-j-davies** [comment]
potentially.... 

Try this last one. the various arguments are separated with a single quote, but if we actually need single quotes in a command - we need to escape them with \\'

-vf \'format=nv12|vaapi,hwupload,scale_vaapi='+width+':'+height+'\'

![Capture](https://user-images.githubusercontent.com/55892693/75776880-c5768d00-5d4c-11ea-9f63-2a5a732b46d7.PNG)

**Comment by 671792320** [comment]
![9](https://user-images.githubusercontent.com/10532894/75777303-b6b1c980-5d90-11ea-820c-dfa2372f3d72.png)

**Comment by 671792320** [comment]
![10](https://user-images.githubusercontent.com/10532894/75777695-5c653880-5d91-11ea-9a19-8aea1486ef7b.png)
![11](https://user-images.githubusercontent.com/10532894/75777696-5cfdcf00-5d91-11ea-94d2-72bd9df7ae4c.png)
It's really strange. After I manually copied the command and added 'quotes' to SRTP, I ran up after the terminal was executed, and real-time images were also displayed on the mobile phone, although carton was slow to respond

**Comment by marcus-j-davies** [comment]
if for what ever reason your environment needs quotes around the output address
do this

change
`const ffmpegStreamArgs = ' -ssrc ' + videoSsrc + ' -f rtp' + ' -srtp_out_suite AES_CM_128_HMAC_SHA1_80' + ' -srtp_out_params ' + videoKey.toString('base64') + ' srtp://' + targetAddress + ':' + targetVideoPort + '?rtcpport=' + targetVideoPort + '&localrtcpport=' + targetVideoPort + '&pkt_size=' + packetsize`

to 
`const ffmpegStreamArgs = ' -ssrc ' + videoSsrc + ' -f rtp' + ' -srtp_out_suite AES_CM_128_HMAC_SHA1_80' + ' -srtp_out_params ' + videoKey.toString('base64') + ' "srtp://' + targetAddress + ':' + targetVideoPort + '?rtcpport=' + targetVideoPort + '&localrtcpport=' + targetVideoPort + '&pkt_size=' + packetsize+'"'`

**Comment by 671792320** [comment]
![12](https://user-images.githubusercontent.com/10532894/75778250-66d40200-5d92-11ea-9d5a-ce7dc089faaf.png)

**Comment by marcus-j-davies** [comment]
Then I am out of ideas...

My only suggestion here is to download NodeJS on your own machine, install ffmpeg, install node-red, and my nodes, and see if you get the same problems.

I think  we need to remove any barrier that could be affecting things.

**Comment by 671792320** [comment]
OK, I'll try your suggestion later

**Comment by 671792320** [comment]
Nodejs

Which version should I use?

**Comment by marcus-j-davies** [comment]
it includes NPM (and doesn't  need to be installed )

https://nodejs.org/dist/v12.16.1/node-v12.16.1-win-x64.zip

**Comment by 671792320** [comment]
Thank you

**Comment by marcus-j-davies** [comment]
Looking at VAAPI, it only runs on Linux, so this may not help in anyway, if you can work out the equivalent for windows, then you can at least check to ensure hardware encoding/rendering does not work.

if it does - then you know your DSM environment is playing havec.

**Comment by 671792320** [comment]
What does that mean?

if it does - then you know your DSM environment is playing havec.

I can't understand machine translation,

You mean vaapi only works in Linux.

If these codes are not valid on Windows

Can it be proved that DSM can run?

**Comment by marcus-j-davies** [comment]
What I mean is :

If you can get windows to run a hardware accelerated video stream, then your DSM or DOCKER  environment is causing you the issues, rather then the node it’s self.

Havoc - misbehaving/causing trouble

I.e your DSM is causing Havoc

Yes, windows does not support VAAPI, so you may need to head over to the FFMPG website to find out how to do hardware encoding/decoding  on windows.

**Comment by 671792320** [comment]
OK, I will try to install nodejs directly on DSM and install noded for testing

**Comment by 671792320** [comment]
After using nodejsv8 to install node red on DSM, the same problem occurs.

**Comment by marcus-j-davies** [comment]
what error invalid filter?

**Comment by 671792320** [comment]
No, what happened was

Stream #0:0: Video: h264 (Main), yuv420p(progressive), 1280x720, 50 fps, 25 tbr, 90k tbn, 100 tbc

Option hwaccel (use HW accelerated decoding) cannot be applied to output url -- you are trying to apply an input option to an output file or vice versa. Move this option before the file it belongs to.

Error parsing options for output file .

Error opening output files: Invalid argument

No longer available for testing, I have deleted the nodejs suite and node red on DSM

**Comment by marcus-j-davies** [comment]
Then I am not sure what the problem is.
I use hardware encoding, and haven't had any problems.

I have exhausted any knowledge I have with ffmpeg (which is not a lot)

my nodes use **child_process** and commands that are used by most homekit camera implementations.

the only thing different is the use of VAAPI - which may be the problem entirely, but i don't have the knowledge to find out.

Once again - Sorry

**Comment by 671792320** [comment]
No, you don't have to say sorry. Instead, I should say thank you. Thank you for your help

Thank you again
